El poema fue acortado.
Ever3tt/github-practice pull request #2
Opened 2023-07-12 21:48 UTC by Ever3tt

@felipemontoya

2023-07-12 22:11 UTC, felipemontoya commented
Explicame más. Me taggeaste en un PR sin contexto. No se que debo hacer ;)

2023-07-12 22:14 UTC, felipemontoya requested changes
Te dejé una petición de cambios que es automatica y una que es manual.

Puedes hacer más commits y subirlos a este branch y el automatico puedes aceptarlo desde la UI.

2023-07-12 22:14 UTC, felipemontoya commented on Poema.txt
> -La comunidad de desarrolladores,
Este verso me gusta. Podrias dejarlo.

2023-07-12 22:14 UTC, felipemontoya commented on Poema.txt
>  resolviendo problemas, creando la magia mía.
```suggestion
resolviendo problemas, creando la magia misma.
```

2023-07-13 14:16 UTC, Ever3tt commented on Poema.txt
> -La comunidad de desarrolladores,
Listo Felipe, lo dejaré

2023-07-13 14:17 UTC, Ever3tt commented on Poema.txt
>  resolviendo problemas, creando la magia mía.
Voy a darle aqui en Resolve conversation para ver que pasa

2023-07-13 14:20 UTC, Ever3tt reviewed
Muy buenos cambios en esta PR

2023-07-13 14:29 UTC, merged

2023-07-13 15:37 UTC, felipemontoya commented
Jaja, de nuevo le diste merge sin esperar a una aprobación.

La conversación no acaba cuando haces los cambios de un review. Normalemente deberías esperar a que el reviewer vuelva a traer comentario o de un approve

2023-07-13 17:14 UTC, Ever3tt commented
Aaaaaa, vale, segun entiendo, tengo que esperar a que el reviewer me deje un comentario, es correcto?